In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('projetintegrer.csv')

In [15]:
df.head()

,Horodateur,Nom d'utilisateur,Âge,Sexe,Niveau d'études,Comment évaluez-vous votre performance académique globale sur une échelle de 1 à 5 ?,Êtes-vous impliqué dans des activités parascolaires ?,"Si oui, veuillez indiquer les activités auxquelles vous participez régulièrement",Comment gérez-vous votre temps entre les activités parascolaires et les études ?,Pensez-vous que la participation à des activités parascolaires a un impact sur votre capacité à gérer votre emploi du temps ?,...,Dans quelle mesure les activités parascolaires contribuent-elles à votre expérience universitaire globale ?,Pensez-vous que la participation à des activités parascolaires a amélioré vos relations avec vos pairs ?,Comment les activités parascolaires ont-elles influencé votre développement personnel et social ?,Quel type d'activités parascolaires préférez-vous ?,À quelle fréquence participez-vous à des activités parascolaires ?,"En moyenne, combien d'heures consacrez-vous chaque semaine à des activités parascolaires ?",Veuillez indiquer votre moyenne générale actuelle sur une échelle de 20.,Combien de fois avez-vous participé à des compétitions ou événements liés à vos activités parascolaires au cours de l'année dernière ?,"Sur une échelle de 1 à 5, à quel point êtes-vous satisfait de votre expérience parascolaire jusqu'à présent ?",Combien de nouvelles compétences avez-vous acquises en participant à des activités parascolaires au cours de votre parcours universitaire ?
0,2023/11/11 5:35:25 PM UTC+1,NaN,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,...,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,2023/11/11 5:36:08 PM UTC+1,NaN,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,...,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,2023/11/11 5:37:03 PM UTC+1,NaN,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,...,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,2023/11/11 5:37:07 PM UTC+1,NaN,18,Homme,1ère année,3,Non,NaN,Discipline,Non,...,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,2023/11/11 5:37:23 PM UTC+1,NaN,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,...,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 22 columns):
 #   Column                                                                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                                                                          --------------  -----
 0   Horodateur                                                                                                                                                      101 non-null    object
 1   Nom d'utilisateur                                                                                                                                               2 non-null      object
 2     Âge                                                                                                                                                           101 non-null    object
 3     Sexe                                                                                                                                                          101 non-null    object
 4     Niveau d'études                                                                                                                                               101 non-null    object
 5     Comment évaluez-vous votre performance académique globale sur une échelle de 1 à 5 ?                                                                          101 non-null    int64
 6     Êtes-vous impliqué dans des activités parascolaires ?                                                                                                         101 non-null    object
 7     Si oui, veuillez indiquer les activités auxquelles vous participez régulièrement                                                                              55 non-null     object
 8     Comment gérez-vous votre temps entre les activités parascolaires et les études ?                                                                              101 non-null    object
 9     Pensez-vous que la participation à des activités parascolaires a un impact sur votre capacité à gérer votre emploi du temps ?                                 101 non-null    object
 10    Avez-vous bénéficié de soutien ou de ressources institutionnelles pour concilier vos activités parascolaires et vos études ?                                  101 non-null    object
 11    Dans quelle mesure votre institution encourage-t-elle la participation aux activités parascolaires tout en maintenant de bonnes performances académiques ?    101 non-null    int64
 12    Dans quelle mesure les activités parascolaires contribuent-elles à votre expérience universitaire globale ?                                                   101 non-null    int64
 13    Pensez-vous que la participation à des activités parascolaires a amélioré vos relations avec vos pairs ?                                                      101 non-null    object
 14    Comment les activités parascolaires ont-elles influencé votre développement personnel et social ?                                                             47 non-null     object
 15    Quel type d'activités parascolaires préférez-vous ?                                                                                                           101 non-null    object
 16    À quelle fréquence participez-vous à des activités parascolaires ?                                                                                            101 non-null    object
 17    En moyenne, combien d'heures consacrez-vous chaque semaine à des activités parascolaires ?                                                                    101 non-null    object
 18    Veuillez indiquer votre moyenne générale actuelle sur une échelle de 20.                                                                                      101 non-null    object
 19    Combien de fois avez-vous participé à des compétitions ou événements liés à vos activités parascolaires au cours de l'année dernière ?                        101 non-null    object
 20    Sur une échelle de 1 à 5, à quel point êtes-vous satisfait de votre expérience parascolaire jusqu'à présent ?                                                 101 non-null    int64
 21    Combien de nouvelles compétences avez-vous acquises en participant à des activités parascolaires au cours de votre parcours universitaire ?                   54 non-null     object
dtypes: int64(4), object(18)
memory usage: 17.5+ KB

In [17]:
df.describe()

,Comment évaluez-vous votre performance académique globale sur une échelle de 1 à 5 ?,Dans quelle mesure votre institution encourage-t-elle la participation aux activités parascolaires tout en maintenant de bonnes performances académiques ?,Dans quelle mesure les activités parascolaires contribuent-elles à votre expérience universitaire globale ?,"Sur une échelle de 1 à 5, à quel point êtes-vous satisfait de votre expérience parascolaire jusqu'à présent ?"
count,101.000000,101.000000,101.000000,101.000000
mean,3.623762,3.445545,3.633663,3.138614
std,0.772677,1.170258,1.083723,1.224987
min,2.000000,1.000000,1.000000,1.000000
25%,3.000000,3.000000,3.000000,2.000000
50%,4.000000,4.000000,4.000000,3.000000
75%,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,5.000000

In [18]:
df.columns = [
    'timestamp',
    'username',
    'age',
    'gender',
    'education_level',
    'academic_performance_rating',
    'extracurricular_involvement',
    'participating_activities',
    'time_management_strategy',
    'impact_on_time_management',
    'institutional_support',
    'institutional_encouragement_rating',
    'extracurricular_contribution_rating',
    'improved_peer_relations',
    'influence_on_personal_development',
    'preferred_activities',
    'frequency_of_participation',
    'weekly_hours_spent_on_activities',
    'current_overall_average',
    'participation_in_events_last_year',
    'satisfaction_rating',
    'skills_acquired_count'
]

df.head()

,timestamp,username,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,...,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,2023/11/11 5:35:25 PM UTC+1,NaN,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,...,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,2023/11/11 5:36:08 PM UTC+1,NaN,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,...,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,2023/11/11 5:37:03 PM UTC+1,NaN,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,...,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,2023/11/11 5:37:07 PM UTC+1,NaN,18,Homme,1ère année,3,Non,NaN,Discipline,Non,...,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,2023/11/11 5:37:23 PM UTC+1,NaN,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,...,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN

In [19]:
df

,timestamp,username,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,...,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,2023/11/11 5:35:25 PM UTC+1,NaN,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,...,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,2023/11/11 5:36:08 PM UTC+1,NaN,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,...,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,2023/11/11 5:37:03 PM UTC+1,NaN,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,...,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,2023/11/11 5:37:07 PM UTC+1,NaN,18,Homme,1ère année,3,Non,NaN,Discipline,Non,...,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,2023/11/11 5:37:23 PM UTC+1,NaN,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,...,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,2023/11/16 8:17:58 AM UTC+1,NaN,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,...,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,2023/11/16 10:13:57 AM UTC+1,NaN,18,Femme,1ère année,4,Non,Non,Dormir,Oui,...,3,Non,Non,Sports,Occasionnellement,0,moins de 12,0,2,0
98,2023/11/16 10:17:17 AM UTC+1,NaN,18 ans,Femme,1ère année,4,Non,Non,Discipline,Oui,...,3,Oui,NaN,Sports,Quotidiennement,0,de 14 à 16,0,2,0
99,2023/11/16 10:21:29 AM UTC+1,NaN,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,...,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2h par jour,de 12 à 14,3,5,NaN
100,2023/11/16 11:18:34 PM UTC+1,NaN,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,...,5,Oui,NaN,Clubs,Occasionnellement,4h,de 12 à 14,0,3,NaN

In [20]:
df.drop_duplicates()

,timestamp,username,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,...,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,2023/11/11 5:35:25 PM UTC+1,NaN,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,...,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,2023/11/11 5:36:08 PM UTC+1,NaN,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,...,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,2023/11/11 5:37:03 PM UTC+1,NaN,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,...,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,2023/11/11 5:37:07 PM UTC+1,NaN,18,Homme,1ère année,3,Non,NaN,Discipline,Non,...,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,2023/11/11 5:37:23 PM UTC+1,NaN,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,...,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,2023/11/16 8:17:58 AM UTC+1,NaN,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,...,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,2023/11/16 10:13:57 AM UTC+1,NaN,18,Femme,1ère année,4,Non,Non,Dormir,Oui,...,3,Non,Non,Sports,Occasionnellement,0,moins de 12,0,2,0
98,2023/11/16 10:17:17 AM UTC+1,NaN,18 ans,Femme,1ère année,4,Non,Non,Discipline,Oui,...,3,Oui,NaN,Sports,Quotidiennement,0,de 14 à 16,0,2,0
99,2023/11/16 10:21:29 AM UTC+1,NaN,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,...,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2h par jour,de 12 à 14,3,5,NaN
100,2023/11/16 11:18:34 PM UTC+1,NaN,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,...,5,Oui,NaN,Clubs,Occasionnellement,4h,de 12 à 14,0,3,NaN

In [22]:
df.drop(columns = "username")

,timestamp,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,...,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,2023/11/11 5:35:25 PM UTC+1,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,Non,...,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,2023/11/11 5:36:08 PM UTC+1,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,Non,...,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,2023/11/11 5:37:03 PM UTC+1,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,Non,...,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,2023/11/11 5:37:07 PM UTC+1,18,Homme,1ère année,3,Non,NaN,Discipline,Non,Non,...,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,2023/11/11 5:37:23 PM UTC+1,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,Non,...,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,2023/11/16 8:17:58 AM UTC+1,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,Non,...,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,2023/11/16 10:13:57 AM UTC+1,18,Femme,1ère année,4,Non,Non,Dormir,Oui,Non,...,3,Non,Non,Sports,Occasionnellement,0,moins de 12,0,2,0
98,2023/11/16 10:17:17 AM UTC+1,18 ans,Femme,1ère année,4,Non,Non,Discipline,Oui,Oui,...,3,Oui,NaN,Sports,Quotidiennement,0,de 14 à 16,0,2,0
99,2023/11/16 10:21:29 AM UTC+1,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,Non,...,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2h par jour,de 12 à 14,3,5,NaN
100,2023/11/16 11:18:34 PM UTC+1,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,Non,...,5,Oui,NaN,Clubs,Occasionnellement,4h,de 12 à 14,0,3,NaN

In [24]:
df = df.drop(columns = "timestamp")
df

,username,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,...,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,NaN,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,Non,...,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,NaN,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,Non,...,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,NaN,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,Non,...,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,NaN,18,Homme,1ère année,3,Non,NaN,Discipline,Non,Non,...,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,NaN,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,Non,...,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,NaN,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,Non,...,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,NaN,18,Femme,1ère année,4,Non,Non,Dormir,Oui,Non,...,3,Non,Non,Sports,Occasionnellement,0,moins de 12,0,2,0
98,NaN,18 ans,Femme,1ère année,4,Non,Non,Discipline,Oui,Oui,...,3,Oui,NaN,Sports,Quotidiennement,0,de 14 à 16,0,2,0
99,NaN,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,Non,...,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2h par jour,de 12 à 14,3,5,NaN
100,NaN,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,Non,...,5,Oui,NaN,Clubs,Occasionnellement,4h,de 12 à 14,0,3,NaN

In [25]:
df = df.drop(columns = "username")
df

,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,institutional_encouragement_rating,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,Non,3,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,Non,4,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,Non,2,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,18,Homme,1ère année,3,Non,NaN,Discipline,Non,Non,4,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,Non,4,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,Non,4,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,18,Femme,1ère année,4,Non,Non,Dormir,Oui,Non,3,3,Non,Non,Sports,Occasionnellement,0,moins de 12,0,2,0
98,18 ans,Femme,1ère année,4,Non,Non,Discipline,Oui,Oui,3,3,Oui,NaN,Sports,Quotidiennement,0,de 14 à 16,0,2,0
99,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,Non,3,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2h par jour,de 12 à 14,3,5,NaN
100,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,Non,5,5,Oui,NaN,Clubs,Occasionnellement,4h,de 12 à 14,0,3,NaN

In [26]:
# Extract only numeric values from the "age" column
df['age'] = df['age'].astype(str).str.extract('(\d+)')

# Convert the "age" column to numeric type
df['age'] = pd.to_numeric(df['age'])

# Print the updated DataFrame
print(df)

     age gender education_level  academic_performance_rating  \
0     21  Femme      4ème année                            5
1     20  Femme      4ème année                            3
2     21  Homme      3ème année                            3
3     18  Homme      1ère année                            3
4     21  Homme      4ème année                            4
..   ...    ...             ...                          ...
96    21  Homme      5ème année                            5
97    18  Femme      1ère année                            4
98    18  Femme      1ère année                            4
99    19  Femme      1ère année                            5
100   22  Femme      4ème année                            4

    extracurricular_involvement participating_activities  \
0                           Non                      NaN
1                           Non                      NaN
2                           Non                     Rien
3                           Non                      NaN
4                           Non                     Foot
..                          ...                      ...
96                          Oui    Computer Science Team
97                          Non                      Non
98                          Non                      Non
99                          Oui         Club associatif
100                         Non                      NaN

    time_management_strategy impact_on_time_management institutional_support  \
0                Flexibilité                       Oui                   Non
1       jfais pas d'activité                       Non                   Non
2               Priorisation                       Oui                   Non
3                 Discipline                       Non                   Non
4                Flexibilité                       Oui                   Non
..                       ...                       ...                   ...
96               Flexibilité                       Oui                   Non
97                    Dormir                       Oui                   Non
98                Discipline                       Oui                   Oui
99             Planification                       Oui                   Non
100             Priorisation                       Oui                   Non

     institutional_encouragement_rating  extracurricular_contribution_rating  \
0                                     3                                    1
1                                     4                                    5
2                                     2                                    2
3                                     4                                    3
4                                     4                                    4
..                                  ...                                  ...
96                                    4                                    5
97                                    3                                    3
98                                    3                                    3
99                                    3                                    4
100                                   5                                    5

    improved_peer_relations influence_on_personal_development  \
0                       Non                               NaN
1                   Pas sûr                               NaN
2                       Oui                               NaN
3                   Pas sûr                               NaN
4                       Oui                               NaN
..                      ...                               ...
96                      Oui                               NaN
97                      Non                               Non
98                      Oui                               NaN
99                  Pas sûr                               NaN
100                     Oui                               NaN

    preferred_activities frequency_of_participation  \
0            Sports;Arts          Occasionnellement
1                   Arts          Occasionnellement
2                 Sports          Occasionnellement
3                 Sports           Hebdomadairement
4                 Sports            Quotidiennement
..                   ...                        ...
96          Sports;Clubs           Hebdomadairement
97                Sports          Occasionnellement
98                Sports            Quotidiennement
99          Sports;Clubs            Quotidiennement
100                Clubs          Occasionnellement

    weekly_hours_spent_on_activities current_overall_average  \
0                                 0h              de 16 à 18
1                                  0              de 16 à 18
2                                 2h              de 12 à 14
3                              30min              de 16 à 18
4                                  2              de 14 à 16
..                               ...                     ...
96                                 3              de 14 à 16
97                                 0             moins de 12
98                                 0              de 14 à 16
99                       2h par jour              de 12 à 14
100                               4h              de 12 à 14

      participation_in_events_last_year  satisfaction_rating  \
0                                     2                    2
1                                     2                    1
2                            Pas encore                    1
3                        Une seule fois                    4
4                                     2                    3
..                                  ...                  ...
96   2 fois par semaine et parfois plus                    5
97                                    0                    2
98                                    0                    2
99                                    3                    5
100                                   0                    3

    skills_acquired_count
0                     NaN
1                     NaN
2              Pas encore
3                       0
4                     NaN
..                    ...
96                    NaN
97                      0
98                      0
99                    NaN
100                   NaN

[101 rows x 20 columns]

In [27]:
df

,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,institutional_encouragement_rating,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,Non,3,1,Non,NaN,Sports;Arts,Occasionnellement,0h,de 16 à 18,2,2,NaN
1,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,Non,4,5,Pas sûr,NaN,Arts,Occasionnellement,0,de 16 à 18,2,1,NaN
2,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,Non,2,2,Oui,NaN,Sports,Occasionnellement,2h,de 12 à 14,Pas encore,1,Pas encore
3,18,Homme,1ère année,3,Non,NaN,Discipline,Non,Non,4,3,Pas sûr,NaN,Sports,Hebdomadairement,30min,de 16 à 18,Une seule fois,4,0
4,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,Non,4,4,Oui,NaN,Sports,Quotidiennement,2,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,Non,4,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,18,Femme,1ère année,4,Non,Non,Dormir,Oui,Non,3,3,Non,Non,Sports,Occasionnellement,0,moins de 12,0,2,0
98,18,Femme,1ère année,4,Non,Non,Discipline,Oui,Oui,3,3,Oui,NaN,Sports,Quotidiennement,0,de 14 à 16,0,2,0
99,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,Non,3,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2h par jour,de 12 à 14,3,5,NaN
100,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,Non,5,5,Oui,NaN,Clubs,Occasionnellement,4h,de 12 à 14,0,3,NaN

In [28]:
# Extract only numeric values from the "weekly_hours_spent_on_activities" column
df['weekly_hours_spent_on_activities'] = df['weekly_hours_spent_on_activities'].astype(str).str.extract('(\d+)')

# Convert the "weekly_hours_spent_on_activities" column to numeric type
df['weekly_hours_spent_on_activities'] = pd.to_numeric(df['weekly_hours_spent_on_activities'])

# Print the updated DataFrame
print(df)

     age gender education_level  academic_performance_rating  \
0     21  Femme      4ème année                            5
1     20  Femme      4ème année                            3
2     21  Homme      3ème année                            3
3     18  Homme      1ère année                            3
4     21  Homme      4ème année                            4
..   ...    ...             ...                          ...
96    21  Homme      5ème année                            5
97    18  Femme      1ère année                            4
98    18  Femme      1ère année                            4
99    19  Femme      1ère année                            5
100   22  Femme      4ème année                            4

    extracurricular_involvement participating_activities  \
0                           Non                      NaN
1                           Non                      NaN
2                           Non                     Rien
3                           Non                      NaN
4                           Non                     Foot
..                          ...                      ...
96                          Oui    Computer Science Team
97                          Non                      Non
98                          Non                      Non
99                          Oui         Club associatif
100                         Non                      NaN

    time_management_strategy impact_on_time_management institutional_support  \
0                Flexibilité                       Oui                   Non
1       jfais pas d'activité                       Non                   Non
2               Priorisation                       Oui                   Non
3                 Discipline                       Non                   Non
4                Flexibilité                       Oui                   Non
..                       ...                       ...                   ...
96               Flexibilité                       Oui                   Non
97                    Dormir                       Oui                   Non
98                Discipline                       Oui                   Oui
99             Planification                       Oui                   Non
100             Priorisation                       Oui                   Non

     institutional_encouragement_rating  extracurricular_contribution_rating  \
0                                     3                                    1
1                                     4                                    5
2                                     2                                    2
3                                     4                                    3
4                                     4                                    4
..                                  ...                                  ...
96                                    4                                    5
97                                    3                                    3
98                                    3                                    3
99                                    3                                    4
100                                   5                                    5

    improved_peer_relations influence_on_personal_development  \
0                       Non                               NaN
1                   Pas sûr                               NaN
2                       Oui                               NaN
3                   Pas sûr                               NaN
4                       Oui                               NaN
..                      ...                               ...
96                      Oui                               NaN
97                      Non                               Non
98                      Oui                               NaN
99                  Pas sûr                               NaN
100                     Oui                               NaN

    preferred_activities frequency_of_participation  \
0            Sports;Arts          Occasionnellement
1                   Arts          Occasionnellement
2                 Sports          Occasionnellement
3                 Sports           Hebdomadairement
4                 Sports            Quotidiennement
..                   ...                        ...
96          Sports;Clubs           Hebdomadairement
97                Sports          Occasionnellement
98                Sports            Quotidiennement
99          Sports;Clubs            Quotidiennement
100                Clubs          Occasionnellement

     weekly_hours_spent_on_activities current_overall_average  \
0                                 0.0              de 16 à 18
1                                 0.0              de 16 à 18
2                                 2.0              de 12 à 14
3                                30.0              de 16 à 18
4                                 2.0              de 14 à 16
..                                ...                     ...
96                                3.0              de 14 à 16
97                                0.0             moins de 12
98                                0.0              de 14 à 16
99                                2.0              de 12 à 14
100                               4.0              de 12 à 14

      participation_in_events_last_year  satisfaction_rating  \
0                                     2                    2
1                                     2                    1
2                            Pas encore                    1
3                        Une seule fois                    4
4                                     2                    3
..                                  ...                  ...
96   2 fois par semaine et parfois plus                    5
97                                    0                    2
98                                    0                    2
99                                    3                    5
100                                   0                    3

    skills_acquired_count
0                     NaN
1                     NaN
2              Pas encore
3                       0
4                     NaN
..                    ...
96                    NaN
97                      0
98                      0
99                    NaN
100                   NaN

[101 rows x 20 columns]

In [29]:
df

,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,institutional_encouragement_rating,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,Non,3,1,Non,NaN,Sports;Arts,Occasionnellement,0.0,de 16 à 18,2,2,NaN
1,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,Non,4,5,Pas sûr,NaN,Arts,Occasionnellement,0.0,de 16 à 18,2,1,NaN
2,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,Non,2,2,Oui,NaN,Sports,Occasionnellement,2.0,de 12 à 14,Pas encore,1,Pas encore
3,18,Homme,1ère année,3,Non,NaN,Discipline,Non,Non,4,3,Pas sûr,NaN,Sports,Hebdomadairement,30.0,de 16 à 18,Une seule fois,4,0
4,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,Non,4,4,Oui,NaN,Sports,Quotidiennement,2.0,de 14 à 16,2,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,Non,4,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3.0,de 14 à 16,2 fois par semaine et parfois plus,5,NaN
97,18,Femme,1ère année,4,Non,Non,Dormir,Oui,Non,3,3,Non,Non,Sports,Occasionnellement,0.0,moins de 12,0,2,0
98,18,Femme,1ère année,4,Non,Non,Discipline,Oui,Oui,3,3,Oui,NaN,Sports,Quotidiennement,0.0,de 14 à 16,0,2,0
99,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,Non,3,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2.0,de 12 à 14,3,5,NaN
100,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,Non,5,5,Oui,NaN,Clubs,Occasionnellement,4.0,de 12 à 14,0,3,NaN

In [30]:
# Replace values in the "participation_in_events_last_year" column
df['participation_in_events_last_year'] = df['participation_in_events_last_year'].replace({
    'Pas encore': 0,
    'Une seule fois': 1,
    '2 fois par semaine et parfois plus': 2
})

# Extract only numeric values from the "participation_in_events_last_year" column
df['participation_in_events_last_year'] = pd.to_numeric(df['participation_in_events_last_year'], errors='coerce')

# Print the updated DataFrame
print(df)

     age gender education_level  academic_performance_rating  \
0     21  Femme      4ème année                            5
1     20  Femme      4ème année                            3
2     21  Homme      3ème année                            3
3     18  Homme      1ère année                            3
4     21  Homme      4ème année                            4
..   ...    ...             ...                          ...
96    21  Homme      5ème année                            5
97    18  Femme      1ère année                            4
98    18  Femme      1ère année                            4
99    19  Femme      1ère année                            5
100   22  Femme      4ème année                            4

    extracurricular_involvement participating_activities  \
0                           Non                      NaN
1                           Non                      NaN
2                           Non                     Rien
3                           Non                      NaN
4                           Non                     Foot
..                          ...                      ...
96                          Oui    Computer Science Team
97                          Non                      Non
98                          Non                      Non
99                          Oui         Club associatif
100                         Non                      NaN

    time_management_strategy impact_on_time_management institutional_support  \
0                Flexibilité                       Oui                   Non
1       jfais pas d'activité                       Non                   Non
2               Priorisation                       Oui                   Non
3                 Discipline                       Non                   Non
4                Flexibilité                       Oui                   Non
..                       ...                       ...                   ...
96               Flexibilité                       Oui                   Non
97                    Dormir                       Oui                   Non
98                Discipline                       Oui                   Oui
99             Planification                       Oui                   Non
100             Priorisation                       Oui                   Non

     institutional_encouragement_rating  extracurricular_contribution_rating  \
0                                     3                                    1
1                                     4                                    5
2                                     2                                    2
3                                     4                                    3
4                                     4                                    4
..                                  ...                                  ...
96                                    4                                    5
97                                    3                                    3
98                                    3                                    3
99                                    3                                    4
100                                   5                                    5

    improved_peer_relations influence_on_personal_development  \
0                       Non                               NaN
1                   Pas sûr                               NaN
2                       Oui                               NaN
3                   Pas sûr                               NaN
4                       Oui                               NaN
..                      ...                               ...
96                      Oui                               NaN
97                      Non                               Non
98                      Oui                               NaN
99                  Pas sûr                               NaN
100                     Oui                               NaN

    preferred_activities frequency_of_participation  \
0            Sports;Arts          Occasionnellement
1                   Arts          Occasionnellement
2                 Sports          Occasionnellement
3                 Sports           Hebdomadairement
4                 Sports            Quotidiennement
..                   ...                        ...
96          Sports;Clubs           Hebdomadairement
97                Sports          Occasionnellement
98                Sports            Quotidiennement
99          Sports;Clubs            Quotidiennement
100                Clubs          Occasionnellement

     weekly_hours_spent_on_activities current_overall_average  \
0                                 0.0              de 16 à 18
1                                 0.0              de 16 à 18
2                                 2.0              de 12 à 14
3                                30.0              de 16 à 18
4                                 2.0              de 14 à 16
..                                ...                     ...
96                                3.0              de 14 à 16
97                                0.0             moins de 12
98                                0.0              de 14 à 16
99                                2.0              de 12 à 14
100                               4.0              de 12 à 14

     participation_in_events_last_year  satisfaction_rating  \
0                                  2.0                    2
1                                  2.0                    1
2                                  0.0                    1
3                                  1.0                    4
4                                  2.0                    3
..                                 ...                  ...
96                                 2.0                    5
97                                 0.0                    2
98                                 0.0                    2
99                                 3.0                    5
100                                0.0                    3

    skills_acquired_count
0                     NaN
1                     NaN
2              Pas encore
3                       0
4                     NaN
..                    ...
96                    NaN
97                      0
98                      0
99                    NaN
100                   NaN

[101 rows x 20 columns]

In [31]:
df

,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,institutional_encouragement_rating,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,21,Femme,4ème année,5,Non,NaN,Flexibilité,Oui,Non,3,1,Non,NaN,Sports;Arts,Occasionnellement,0.0,de 16 à 18,2.0,2,NaN
1,20,Femme,4ème année,3,Non,NaN,jfais pas d'activité,Non,Non,4,5,Pas sûr,NaN,Arts,Occasionnellement,0.0,de 16 à 18,2.0,1,NaN
2,21,Homme,3ème année,3,Non,Rien,Priorisation,Oui,Non,2,2,Oui,NaN,Sports,Occasionnellement,2.0,de 12 à 14,0.0,1,Pas encore
3,18,Homme,1ère année,3,Non,NaN,Discipline,Non,Non,4,3,Pas sûr,NaN,Sports,Hebdomadairement,30.0,de 16 à 18,1.0,4,0
4,21,Homme,4ème année,4,Non,Foot,Flexibilité,Oui,Non,4,4,Oui,NaN,Sports,Quotidiennement,2.0,de 14 à 16,2.0,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,21,Homme,5ème année,5,Oui,Computer Science Team,Flexibilité,Oui,Non,4,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3.0,de 14 à 16,2.0,5,NaN
97,18,Femme,1ère année,4,Non,Non,Dormir,Oui,Non,3,3,Non,Non,Sports,Occasionnellement,0.0,moins de 12,0.0,2,0
98,18,Femme,1ère année,4,Non,Non,Discipline,Oui,Oui,3,3,Oui,NaN,Sports,Quotidiennement,0.0,de 14 à 16,0.0,2,0
99,19,Femme,1ère année,5,Oui,Club associatif,Planification,Oui,Non,3,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2.0,de 12 à 14,3.0,5,NaN
100,22,Femme,4ème année,4,Non,NaN,Priorisation,Oui,Non,5,5,Oui,NaN,Clubs,Occasionnellement,4.0,de 12 à 14,0.0,3,NaN

In [46]:
# Remove "ème année" and "ère année" from the "education_level" column
df['education_level'] = df['education_level'].str.replace(r'ème année|ère année', '', regex=True)

# Print the updated DataFrame
print(df['education_level'])

0      4
1      4
2      3
3      1
4      4
      ..
96     5
97     1
98     1
99     1
100    4
Name: education_level, Length: 101, dtype: object

In [47]:
df

,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,institutional_encouragement_rating,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,21,Femme,4,5,Non,NaN,Flexibilité,Oui,Non,3,1,Non,NaN,Sports;Arts,Occasionnellement,0.0,NaN,2.0,2,NaN
1,20,Femme,4,3,Non,NaN,jfais pas d'activité,Non,Non,4,5,Pas sûr,NaN,Arts,Occasionnellement,0.0,NaN,2.0,1,NaN
2,21,Homme,3,3,Non,Rien,Priorisation,Oui,Non,2,2,Oui,NaN,Sports,Occasionnellement,2.0,NaN,0.0,1,Pas encore
3,18,Homme,1,3,Non,NaN,Discipline,Non,Non,4,3,Pas sûr,NaN,Sports,Hebdomadairement,30.0,NaN,1.0,4,0
4,21,Homme,4,4,Non,Foot,Flexibilité,Oui,Non,4,4,Oui,NaN,Sports,Quotidiennement,2.0,NaN,2.0,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,21,Homme,5,5,Oui,Computer Science Team,Flexibilité,Oui,Non,4,5,Oui,NaN,Sports;Clubs,Hebdomadairement,3.0,NaN,2.0,5,NaN
97,18,Femme,1,4,Non,Non,Dormir,Oui,Non,3,3,Non,Non,Sports,Occasionnellement,0.0,NaN,0.0,2,0
98,18,Femme,1,4,Non,Non,Discipline,Oui,Oui,3,3,Oui,NaN,Sports,Quotidiennement,0.0,NaN,0.0,2,0
99,19,Femme,1,5,Oui,Club associatif,Planification,Oui,Non,3,4,Pas sûr,NaN,Sports;Clubs,Quotidiennement,2.0,NaN,3.0,5,NaN
100,22,Femme,4,4,Non,NaN,Priorisation,Oui,Non,5,5,Oui,NaN,Clubs,Occasionnellement,4.0,NaN,0.0,3,NaN

In [48]:
df = df.fillna(0)

In [49]:
df

,age,gender,education_level,academic_performance_rating,extracurricular_involvement,participating_activities,time_management_strategy,impact_on_time_management,institutional_support,institutional_encouragement_rating,extracurricular_contribution_rating,improved_peer_relations,influence_on_personal_development,preferred_activities,frequency_of_participation,weekly_hours_spent_on_activities,current_overall_average,participation_in_events_last_year,satisfaction_rating,skills_acquired_count
0,21,Femme,4,5,Non,0,Flexibilité,Oui,Non,3,1,Non,0,Sports;Arts,Occasionnellement,0.0,0.0,2.0,2,0
1,20,Femme,4,3,Non,0,jfais pas d'activité,Non,Non,4,5,Pas sûr,0,Arts,Occasionnellement,0.0,0.0,2.0,1,0
2,21,Homme,3,3,Non,Rien,Priorisation,Oui,Non,2,2,Oui,0,Sports,Occasionnellement,2.0,0.0,0.0,1,Pas encore
3,18,Homme,1,3,Non,0,Discipline,Non,Non,4,3,Pas sûr,0,Sports,Hebdomadairement,30.0,0.0,1.0,4,0
4,21,Homme,4,4,Non,Foot,Flexibilité,Oui,Non,4,4,Oui,0,Sports,Quotidiennement,2.0,0.0,2.0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,21,Homme,5,5,Oui,Computer Science Team,Flexibilité,Oui,Non,4,5,Oui,0,Sports;Clubs,Hebdomadairement,3.0,0.0,2.0,5,0
97,18,Femme,1,4,Non,Non,Dormir,Oui,Non,3,3,Non,Non,Sports,Occasionnellement,0.0,0.0,0.0,2,0
98,18,Femme,1,4,Non,Non,Discipline,Oui,Oui,3,3,Oui,0,Sports,Quotidiennement,0.0,0.0,0.0,2,0
99,19,Femme,1,5,Oui,Club associatif,Planification,Oui,Non,3,4,Pas sûr,0,Sports;Clubs,Quotidiennement,2.0,0.0,3.0,5,0
100,22,Femme,4,4,Non,0,Priorisation,Oui,Non,5,5,Oui,0,Clubs,Occasionnellement,4.0,0.0,0.0,3,0